name: Flutter CI

on:
  pull_request:
    branches: [ "main","gourav"]
  push:
    branches: [ "main","gourav" ]

jobs:
  analyze-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable      # <-- change to "beta" only if your project needs it

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (static checks)
        run: flutter analyze

      - name: Run unit tests
        run: flutter test
